[package]
name = "bibq"
version = "0.1.0"
edition = "2021"

[dependencies]
biblatex = { version = "0.10.0", features = ["serde"] }
clap = { version = "4.5.36", features = ["derive"] }
miette = { version = "7.5.0", features = ["fancy"] }
rayon = "1.10.0"
regex = "1.11.1"
thiserror = "2.0.12"
